DELETE FROM concerns;
INSERT INTO concerns VALUES
(NULL, "Acne"),
(NULL, "Aging"),
(NULL, "Clogged"),
(NULL, "Dryness"),
(NULL, "Dullness"),
(NULL, "Irritated"),
(NULL, "Oiliness"),
(NULL, "Scars");

DELETE FROM beauty_types;
INSERT INTO beauty_types VALUES
(NULL, "Starfish", "What does that mean? A Starfish often has large pores. Your forehead, nose and chin (the T-Zone) are often shiny or greasy, and sometimes the C-Zone as well. Under the skin there is fatty tissue which creates higher sebum production with the probability of blackheads, blemishes and acne. Severe acne can lead to scarring, hyperpigmentation and pitted skin. Glycolic products are highly effective at treating oily to acne skin. Acne caused by bacteria on the skin responds well to oxygen or peroxide products. Steam and deep cleansing treatments are also recommended. Great care must be taken to avoid using too many products that will dry (alcohol, salicylic acid, or sulfur) the skin as it will lead to peeling or irritation or the skin will often retaliate by producing more sebum. Its best to take the approach of balancing the skin with gentle products like tea tree oil. Many snail products are also great for this."),
(NULL, "Snail", "What does that mean? A Snail has areas of normal, oily and dry skin existing at one time. Your skin is generally dry in the cheek area, while oily in the T-Zone (forehead, nose and chin). Using different products for different areas of your face is recommended. Like a cream moisturizer for the cheeks and a gel for your T-Zone."),
(NULL, "Bee", "What does that mean? A Bee is not too oily or too dry in any particular area. Your skin is firm with a healthy glow and a smooth texture with small pores. Your skin is not easily irritated and blemishes are rare. But it is still super important to protect your skin by using sunscreen and proper hygiene, to prevent skin care problems from forming."),
(NULL, "Butterfly", "What does that mean? A Butterfly’s skin may not able to sustain a significant moisture level and irritation can occur. It is sometimes characterized by redness, roughness, and flaking or peeling skin if not properly moisturized. Your skin could be tight, lack suppleness and fine lines appear may around your eyes and lips. Products that exfoliate and nourish the skin are recommended. Actives (see “Exfoliants” below) followed by an appropriate moisturizer are effective (see “The Skin Care Routine, The Steps & The Why” for more details). Use of a humidifier or steam treatments are excellent ways to replenish lost natural moisture. Heavier moisturizers and occlusives to seal everything in can be beneficial. Sleeping packs can add an extra, moisturizing step (see “The Product Categories & What They Do”)."),
(NULL, "Dragonfly", "What does that mean? A Dragonfly’s skin may be easily irritated by soaps, touch, or other substances in the environment. It may be thin, dry, with fine pores. It may become red and damaged easily, while appearing blotchy and irritated. Broken capillaries and vessels beneath the surface may be apparent. Great care must be taken to not over-stimulate your sensitive skin and hypoallergenic products should be used. Avoid harsh detergents and products with alcohol, dyes and perfumes. Your skin could be dry and flaky in some areas, while seeming excessively oily in others. If so, it could be dehydrated, which is not a skin type as much as an issue that needs to be addressed. With proper care, dehydrated skin can be fixed.");

DELETE FROM product_categories;
INSERT INTO product_categories VALUES
(NULL, "Cleanser 1", "All of them work off the premise of 'like dissolves like' and are usually meant to be cleaned off with another cleanser, or come with emulsifying agents mixed in to rinse off with water, or are meant to be wiped off the face without adding additional water. These include oil cleansers, cold-cream cleansers, cream cleansers, balm cleansers which are basically oil cleansers in solid form until they melt onto your skin, and sherbet cleansers which are very close to balm cleansers although with a different texture pre-application. Also, water-based cleansers. There are cleansing waters which are very gentle and good for people with dry and sensitive skin which doesn't need a heavy cleansing."),
(NULL, "Cleanser 2", "Most commonly foaming cleansers, but can also include gel or milk. For the foaming type especially it is important to select a cleanser with the correct ph. Foaming cleansers usually have a high ph since those with a lower ph may be too gentle to fully remove makeup. However that is why the double cleanse (as described below) is so important. The 1st cleanser removes makeup & sunscreen so that you can use a foaming cleanser for your 2nd step that has the correct ph of 5.5. Higher ph cleansers can strip the skin and weaken the acid mantle barrier making you more prone to acne and wrinkles. When attempting to fix dehydrated skin this plays a huge role."),
(NULL, "Toner/Skin/Treatment Essence", "Toner: Asian toners are very different from western toners, which are typically astringents and include alcohol. Asian toners are usually of the “hydrating variety” but there are a few kinds. If you are not using a ‘first essence’, you would move straight to the hydrating toner.  Thus, you aren’t applying a product only to wipe it off with the toner, the toner is the next layer.
1) 'First' Essences, such as the Missha First Treatment Essence, Mizon Skin Power Original First Essence, and any other product that has instructions to be applied first after basic cleansing.  If you have multiple 'first' type products, use the 'fat over lean' rule above. If you use a first essence and a hydrating toner, first essence comes first. 2) Hydrating Toners, such as the Hada Labo Gokujyun, Mizon Mela Defense White Boosting Toner, Holika Holika Don't Worry Bee Care Calendula Toner, Skinfood Gold Kiwi Toner, and all 'toners' that are meant as a layer of skincare, bringing moisture or nourishment to the skin.  Note: these are very different than 'cleansing' type toners, which would be included in your 'Basic Cleansing' steps. 3) Prepping or Cleansing Toners meant to lower the pH of your skin in preparation for later steps, and has a low enough pH, such as the Mizon AHA & BHA Daily Clean toner, used to force down the pH of the skin after cleansing and before applying actives (chemical exfoliants, Vitamin C serums)."),
(NULL, "Essence/Ampoule/Serum", "Typically a liquid with a thicker consistency (it varies). Each is meant to target a specific skin concern. Can use one or many. There are many different kinds, meant for many different things and all different skin types. This step offers the greatest chance for ‘customization’ in your routine. Worried about age prevention? Plenty of serums for that (and use sunscreen!!!!) Dull complexion? Try a propolis ampoule. Acne or hyperpigmentation? A tea tree essence. Huge range in prices, but typically you only need a few drops for each application. Vitamin C serum is technically a serum, but also an exfoliant (see “Exfoliant” below)."),
(NULL, "Moisturizer/Lotion/Emulsion", "Includes light lotions (sometimes known as ‘emulsions’), gels,  and creams (including eye creams). It’s best to mainly layer creams/occlusives in the areas of your face that are normal, or dry. Occlusives (the heaviest gels or creams) also act as a layer that ‘seals’ everything else in. For those with oily or combination cream, it’s best to stick with gels or light lotions on any part of your face that is not dry. Although it may seem counterintuitive, it’s important to moisturize every part of the face, even the oily parts. Otherwise your skin may become dehydrated and begin to produce even more oil to compensate."),
(NULL, "Exfoliant", "Also known as ‘actives’, these are products that have a scientific pedigree when it comes to their benefits for skin.  Very helpful (when used correctly) for many skin troubles (acne, large pores, clogged pores, sun damage, hyperpigmentation, uneven skin tone, wrinkles)."),
(NULL, "Mask", "Known as the “gateway drug” when it comes to Asian beauty products. Good masks can show noticeable results (for example brightening) after just one use. However these results usually don’t last longer than 24-48 hours. There are several different types, the most common are Sheet masks, thin, treatment-soaked pieces of cloth (usually cotton) cut to fit your face. Hydrogel masks are very similar, but are made of a thin gel, cut in the shape of your face. Hydrogel masks lock in moisture much better than cotton, so they usually provide better results and are more expensive. Clay and other wash off masks are a thick, gooey consistency. Apply to clean dry face and rinse off when the clay has dried. Clay masks are especially are good for oily or acne prone skin. Sleeping masks or packs are the final step in the evening skin care routine (optional). Usually for extra hydration. Should be rinsed off in the morning."),
(NULL, "Sunscreen", "Korean, and especially Japanese sunscreens in general are far superior to those bought in Europe, and especially the U.S. Asian sunscreens protect skin better from both UVA and UVB rays, and are more “cosmetically elegant”. They are far less likely leave a white cast, are much less greasy, feel better on the skin, look better under makeup, and just look better in general than their U.S. counterparts. There are multiple ingredients used in Asian sunscreens that have not been approved by the FDA. Japan and Korea takes their sun damage prevention very seriously. It should be noted that the #1 best way to prevent wrinkles, spots, and other signs of aging is by using sunscreen every single day, on any portion of your skin that will be exposed. How much should you use? A rather controversial topic in the skin care world, for a long time it was believed that you should apply at least 1/4 teaspoon to your face, plus more for your neck, arms, and any other exposed areas. However more recently it has been made clear that the 1/4 teaspoon measurement (which is actually quite a lot for just your face) was based on a study in which the test subjects were all men with face sizes in the 90th percentile (men with faces larger than most). So it’s likely many people need less. Each application is for 2 hours of time spent outdoors. So if you are only outside during the day on your way to & from work and on your lunch break, and that adds up to less than 2 hours, than a single application of (good) sunscreen, 20 minutes before you leave the house in the morning should be sufficient.");

DELETE FROM products;
INSERT INTO products VALUES
(NULL, "LeeJiHam", "Tea Tree 90 Essence", 40, "An age-old remedy for a spectrum of skin conditions including acne and eczema, tea tree oil reduces redness, soothes, and rejuvinates the skin. Formulated with 90% natural tea tree extract, you can feel its power of revitalization as Tea Tree 90 Essence alleviates uneven skin tone, minimizes redness, refreshes the skin, and improves overall complexion. With over 800x more Vitamin C than an apple, your skin will thank you for the invigorating treatment that leaves it rejuvinated and radiant.", 1, 4, 1),
(NULL, "Skinfood", "Peach Sake Pore Serum", 15, "Description: Rich in Vitamins A, C and Silica Powder derived from rice sake and peach extract, this product is a multi-functional item. Not only does this serum moisture the skin but also helps prevent sebum production while simultaneously minimizing the appearance of pores.", 1, 4, 7),
(NULL, "Banila Co.", "Clean It Zero", 15, "Heralded as one of Allure Magazine's (Korea) Editor's Picks, this award-winning hypoallergenic cleansing cream has finally hit our stores. This unique product applies as a solid balm and then transforms into a silky oil on the skin as you massage the product on your skin. Dissolving the most stubborn makeup and removing any impurities from your skin while keeping your skin's essential oils in tact. Formulated with various Extracts and Vitamins like Papaya Extract and Vitamin C, your skin will feel clean, smooth, and radiant.", 4, 1, 5),
(NULL, "Leaders", "Teatree Relaxing Renewal Mask", 2, "This soothing tea tree sheet mask is infused with organic leaf extracts (birch, hazelnut and olive) that helps control oily, irritated skin and reduces the appearance of unbalanced skin. Its natural extracts repairs damage on the skin and helps exfoliate, purify and soften the complexion giving the skin a radiant glow.", 2, 7, 1),
(NULL, "Missha", "Time Revolution The First Treatment Essence", 50, "Heralded as a miracle water, the First Treatment Essence is a powerful skin experience. The 80% yeast concentrate energizes your skin cells with regenerative properties. First Treatment Essence replenishes elasticity, revives skin tone, and reveals softened, soothed skin. Signs of aging will be rebuffed and the old will be replaced by the new - bringing you closer to a flawless complexion. This essence hydrates, restores, rejuvenates, and gives you a glowing complexion. This product contains Niacinamide, a Vitamin B3 component, to improve skin elasticity, enhance skin barrier function, and revive skin tone and texture. DN-Aid, made from Cassia-Alata Extract, provides vitality to aging skin, protects DNA from aging caused by UV rays, and promotes restoration of damaged DNA.", 2, 3, 2),
(NULL, "Elizavecca", "Milky Piggy Carbonated Bubble Clay Mask", 9, "This bubble clay mask is both a deep-cleansing makeup remover and pore cleanser in one! With its special formulation of charcoal powder, it deeply penetrates the pores to thoroughly get rid of deep-seated dirt while supplying proper nutrients to keep the skin healthy and supple. It not only cleanses, refines and tightens pores but it also helps control excessive sebum which usually causes the pores to be clogged.", 2, 7, 3);


DELETE FROM users;
INSERT INTO users VALUES
(NULL, "jessica@gmail.com", "mypass", "Jessica", "Simpson", "90210", 1, "Oily", "Oily"),
(NULL, "britney@gmail.com", "mypass", "Britney", "Spears", "90210", 1, "Oily", "Oily");


DELETE FROM ratings;
INSERT INTO ratings VALUES
(NULL, 1, 1, 5, "I love this stuff. Helps with everything!"),
(NULL, 1, 2, 1, "I hate this stuff. Makes everything worse!");